# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/lgoo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playerHand = QtWidgets.QLabel(self.centralwidget)
        self.playerHand.setGeometry(QtCore.QRect(120, 140, 281, 281))
        self.playerHand.setText("")
        self.playerHand.setPixmap(QtGui.QPixmap("img/rock.png"))
        self.playerThrow = 2
        self.playerHand.setScaledContents(True)
        self.playerHand.setObjectName("playerHand")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(120, 420, 171, 51))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 420, 171, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 420, 171, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.cpuHand = QtWidgets.QLabel(self.centralwidget)
        self.cpuHand.setGeometry(QtCore.QRect(440, 0, 211, 191))
        self.cpuHand.setText("")
        self.cpuHand.setPixmap(QtGui.QPixmap("img/frock.png"))
        self.cpuHand.setScaledContents(True)
        self.cpuHand.setObjectName("cpuHand")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 301, 141))
        font = QtGui.QFont()
        font.setFamily("Vladimir Script")
        font.setPointSize(72)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scoreboard = QtWidgets.QLabel(self.centralwidget)
        self.scoreboard.setGeometry(QtCore.QRect(310, 480, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.scoreboard.setFont(font)
        self.scoreboard.setObjectName("scoreboard")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect push buttons to functions that
        # will connect the images to their labels
        self.pushButton_1.clicked.connect(self.showScissors)
        self.pushButton_2.clicked.connect(self.showPaper)
        self.pushButton_3.clicked.connect(self.showRock)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPR"))
        self.pushButton_1.setText(_translate("MainWindow", "Scissors"))
        self.pushButton_2.setText(_translate("MainWindow", "Paper"))
        self.pushButton_3.setText(_translate("MainWindow", "Rock"))
        self.setLabel("")
        self.playerScore = 0
        self.cpuScore = 0
        self.setScores()
        self.scoreboard.setText(_translate("MainWindow", "0-0"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))

    def setLabel(self, text):
        """ Sets the label used to display above player hand. """
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", text))

    def setScores(self):
        """ Sets the scoreboard based on the player/cpu scores """
        _translate = QtCore.QCoreApplication.translate
        scoreboardString = "{}-{}".format(str(self.playerScore), str(self.cpuScore))
        self.scoreboard.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreboard.setText(_translate("MainWindow", str(scoreboardString)))

    def showRock(self):
        ''' Set rock image to player label '''
        self.playerHand.setPixmap(QtGui.QPixmap("img/rock.png"))
        self.playerThrow = 2

    def showCpuRock(self):
        ''' Set rock image to cpu label '''
        self.cpuHand.setPixmap(QtGui.QPixmap("img/frock.png"))

    def showPaper(self):
        ''' Set paper image to player label '''
        self.playerHand.setPixmap(QtGui.QPixmap("img/paper.png"))
        self.playerThrow = 1

    def showCpuPaper(self):
        ''' Set paper image to cpu label '''
        self.cpuHand.setPixmap(QtGui.QPixmap("img/fpaper.png"))

    def showScissors(self):
        ''' Set scissors image to player label '''
        self.playerHand.setPixmap(QtGui.QPixmap("img/scissors.png"))
        self.playerThrow = 0
    
    def showCpuScissors(self):
        ''' Set scissors image to cpu label '''
        self.cpuHand.setPixmap(QtGui.QPixmap("img/fscissors.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
